"""atualizaçao

Revision ID: 6c61bba9840c
Revises: dc004624f45e
Create Date: 2025-02-27 13:31:25.906510

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c61bba9840c'
down_revision: Union[str, None] = 'dc004624f45e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('server', sa.Column('email', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('server', 'email')
    # ### end Alembic commands ###
