"""atualizaçao 2

Revision ID: 6e9f18b08ef3
Revises: 6c61bba9840c
Create Date: 2025-02-27 13:32:53.758716

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e9f18b08ef3'
down_revision: Union[str, None] = '6c61bba9840c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('server', sa.Column('name', sa.String(), nullable=False))
    op.drop_column('server', 'email')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('server', sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('server', 'name')
    # ### end Alembic commands ###
