"""atualizaçao 3

Revision ID: 6f82552fdeae
Revises: 6e9f18b08ef3
Create Date: 2025-02-27 14:59:31.239659

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f82552fdeae'
down_revision: Union[str, None] = '6e9f18b08ef3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
