"""novas tabelas e edições

Revision ID: 9155331392fe
Revises: 3c0739684c60
Create Date: 2025-02-26 21:07:43.799511

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9155331392fe'
down_revision: Union[str, None] = '3c0739684c60'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('server',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_server_id'), 'server', ['id'], unique=False)
    op.create_foreign_key(None, 'sensor_data', 'sensor_data', ['server_ulid'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sensor_data', type_='foreignkey')
    op.drop_index(op.f('ix_server_id'), table_name='server')
    op.drop_table('server')
    # ### end Alembic commands ###
